name: "units-test"
on:
  push:
    branches:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # # test action directly
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ./
  #     with:
  #       webhookUrl: www.test.com
  #       application: XYZ12345678ABC
  #       services: web,console,job
  #       version: ${{ github.sha }}
